//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPCC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLPCC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BackUp {
            get {
                object obj = ResourceManager.GetObject("BackUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackUp1 {
            get {
                object obj = ResourceManager.GetObject("BackUp1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BaoCao {
            get {
                object obj = ResourceManager.GetObject("BaoCao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BaoCao1 {
            get {
                object obj = ResourceManager.GetObject("BaoCao1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BCUT {
            get {
                object obj = ResourceManager.GetObject("BCUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BCUT_Loai {
            get {
                object obj = ResourceManager.GetObject("BCUT_Loai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BCUT_Loai1 {
            get {
                object obj = ResourceManager.GetObject("BCUT_Loai1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BCUT1 {
            get {
                object obj = ResourceManager.GetObject("BCUT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BKNuocNgoai {
            get {
                object obj = ResourceManager.GetObject("BKNuocNgoai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BKNuocNgoai1 {
            get {
                object obj = ResourceManager.GetObject("BKNuocNgoai1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BKNuocNgoai11 {
            get {
                object obj = ResourceManager.GetObject("BKNuocNgoai11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BKNuocNgoai2 {
            get {
                object obj = ResourceManager.GetObject("BKNuocNgoai2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BKTrongNuoc {
            get {
                object obj = ResourceManager.GetObject("BKTrongNuoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BKTrongNuoc1 {
            get {
                object obj = ResourceManager.GetObject("BKTrongNuoc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blockdevice {
            get {
                object obj = ResourceManager.GetObject("blockdevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blockdevice1 {
            get {
                object obj = ResourceManager.GetObject("blockdevice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BPGhiSo {
            get {
                object obj = ResourceManager.GetObject("BPGhiSo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BPGhiSo1 {
            get {
                object obj = ResourceManager.GetObject("BPGhiSo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BPQT {
            get {
                object obj = ResourceManager.GetObject("BPQT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BPQT1 {
            get {
                object obj = ResourceManager.GetObject("BPQT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BuuKienNN {
            get {
                object obj = ResourceManager.GetObject("BuuKienNN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BuuKienNN1 {
            get {
                object obj = ResourceManager.GetObject("BuuKienNN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BuuKienTN {
            get {
                object obj = ResourceManager.GetObject("BuuKienTN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BuuKienTN1 {
            get {
                object obj = ResourceManager.GetObject("BuuKienTN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BuuphamNN {
            get {
                object obj = ResourceManager.GetObject("BuuphamNN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BuuphamNN1 {
            get {
                object obj = ResourceManager.GetObject("BuuphamNN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChauLuc {
            get {
                object obj = ResourceManager.GetObject("ChauLuc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChauLuc1 {
            get {
                object obj = ResourceManager.GetObject("ChauLuc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChonNgayLV {
            get {
                object obj = ResourceManager.GetObject("ChonNgayLV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChonNgayLV1 {
            get {
                object obj = ResourceManager.GetObject("ChonNgayLV1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chuc_nang {
            get {
                object obj = ResourceManager.GetObject("Chuc_nang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chuc_nang1 {
            get {
                object obj = ResourceManager.GetObject("Chuc_nang1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CongNo {
            get {
                object obj = ResourceManager.GetObject("CongNo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CongNo1 {
            get {
                object obj = ResourceManager.GetObject("CongNo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ControlPanel {
            get {
                object obj = ResourceManager.GetObject("ControlPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ControlPanel1 {
            get {
                object obj = ResourceManager.GetObject("ControlPanel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTN {
            get {
                object obj = ResourceManager.GetObject("CTN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTN1 {
            get {
                object obj = ResourceManager.GetObject("CTN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTQT {
            get {
                object obj = ResourceManager.GetObject("CTQT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CTQT1 {
            get {
                object obj = ResourceManager.GetObject("CTQT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DanhMuc {
            get {
                object obj = ResourceManager.GetObject("DanhMuc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DanhMuc1 {
            get {
                object obj = ResourceManager.GetObject("DanhMuc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DanhMucBuuCuc {
            get {
                object obj = ResourceManager.GetObject("DanhMucBuuCuc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DanhMucBuuCuc1 {
            get {
                object obj = ResourceManager.GetObject("DanhMucBuuCuc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DanhMucVung {
            get {
                object obj = ResourceManager.GetObject("DanhMucVung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DanhMucVung1 {
            get {
                object obj = ResourceManager.GetObject("DanhMucVung1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_comit {
            get {
                object obj = ResourceManager.GetObject("db_comit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db_comit1 {
            get {
                object obj = ResourceManager.GetObject("db_comit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoiKiem {
            get {
                object obj = ResourceManager.GetObject("DoiKiem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoiKiem1 {
            get {
                object obj = ResourceManager.GetObject("DoiKiem1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoiMatKhau {
            get {
                object obj = ResourceManager.GetObject("DoiMatKhau", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoiMatKhau1 {
            get {
                object obj = ResourceManager.GetObject("DoiMatKhau1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoiMK {
            get {
                object obj = ResourceManager.GetObject("DoiMK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoiMK1 {
            get {
                object obj = ResourceManager.GetObject("DoiMK1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoiNguoiDung {
            get {
                object obj = ResourceManager.GetObject("DoiNguoiDung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoiNguoiDung1 {
            get {
                object obj = ResourceManager.GetObject("DoiNguoiDung1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoiSoat {
            get {
                object obj = ResourceManager.GetObject("DoiSoat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoiSoat1 {
            get {
                object obj = ResourceManager.GetObject("DoiSoat1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dongchuyenthu {
            get {
                object obj = ResourceManager.GetObject("dongchuyenthu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dongchuyenthu1 {
            get {
                object obj = ResourceManager.GetObject("dongchuyenthu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormNhap {
            get {
                object obj = ResourceManager.GetObject("FormNhap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormNhap1 {
            get {
                object obj = ResourceManager.GetObject("FormNhap1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gohome {
            get {
                object obj = ResourceManager.GetObject("gohome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gohome1 {
            get {
                object obj = ResourceManager.GetObject("gohome1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap he_thong {
            get {
                object obj = ResourceManager.GetObject("he_thong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap he_thong1 {
            get {
                object obj = ResourceManager.GetObject("he_thong1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HeThong {
            get {
                object obj = ResourceManager.GetObject("HeThong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HeThong1 {
            get {
                object obj = ResourceManager.GetObject("HeThong1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kate {
            get {
                object obj = ResourceManager.GetObject("kate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kate1 {
            get {
                object obj = ResourceManager.GetObject("kate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kdmconfig {
            get {
                object obj = ResourceManager.GetObject("kdmconfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kdmconfig1 {
            get {
                object obj = ResourceManager.GetObject("kdmconfig1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kenolaba {
            get {
                object obj = ResourceManager.GetObject("kenolaba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kenolaba1 {
            get {
                object obj = ResourceManager.GetObject("kenolaba1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KetNoiCSDL {
            get {
                object obj = ResourceManager.GetObject("KetNoiCSDL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KetNoiCSDL1 {
            get {
                object obj = ResourceManager.GetObject("KetNoiCSDL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KetNoiDL {
            get {
                object obj = ResourceManager.GetObject("KetNoiDL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KetNoiDL1 {
            get {
                object obj = ResourceManager.GetObject("KetNoiDL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kexi {
            get {
                object obj = ResourceManager.GetObject("kexi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kexi1 {
            get {
                object obj = ResourceManager.GetObject("kexi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Khachang {
            get {
                object obj = ResourceManager.GetObject("Khachang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Khachang1 {
            get {
                object obj = ResourceManager.GetObject("Khachang1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KhaiThacBPBK {
            get {
                object obj = ResourceManager.GetObject("KhaiThacBPBK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KhaiThacBPBK1 {
            get {
                object obj = ResourceManager.GetObject("KhaiThacBPBK1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kpresenter {
            get {
                object obj = ResourceManager.GetObject("kpresenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kpresenter1 {
            get {
                object obj = ResourceManager.GetObject("kpresenter1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kuser {
            get {
                object obj = ResourceManager.GetObject("kuser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kuser1 {
            get {
                object obj = ResourceManager.GetObject("kuser1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lapbaocao {
            get {
                object obj = ResourceManager.GetObject("Lapbaocao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lapbaocao1 {
            get {
                object obj = ResourceManager.GetObject("Lapbaocao1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lassists {
            get {
                object obj = ResourceManager.GetObject("lassists", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lassists1 {
            get {
                object obj = ResourceManager.GetObject("lassists1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Login_Manager {
            get {
                object obj = ResourceManager.GetObject("Login Manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Maintenance {
            get {
                object obj = ResourceManager.GetObject("Maintenance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Maintenance1 {
            get {
                object obj = ResourceManager.GetObject("Maintenance1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NgayLamViec {
            get {
                object obj = ResourceManager.GetObject("NgayLamViec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NgayLamViec1 {
            get {
                object obj = ResourceManager.GetObject("NgayLamViec1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NhomNguoiDung {
            get {
                object obj = ResourceManager.GetObject("NhomNguoiDung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NhomNguoiDung1 {
            get {
                object obj = ResourceManager.GetObject("NhomNguoiDung1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NVDacBiet {
            get {
                object obj = ResourceManager.GetObject("NVDacBiet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NVDacBiet1 {
            get {
                object obj = ResourceManager.GetObject("NVDacBiet1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PhatHanh {
            get {
                object obj = ResourceManager.GetObject("PhatHanh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PhatHanh1 {
            get {
                object obj = ResourceManager.GetObject("PhatHanh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PhucHoiDL {
            get {
                object obj = ResourceManager.GetObject("PhucHoiDL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PhucHoiDL1 {
            get {
                object obj = ResourceManager.GetObject("PhucHoiDL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PhucHoiDuLieu {
            get {
                object obj = ResourceManager.GetObject("PhucHoiDuLieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PhucHoiDuLieu1 {
            get {
                object obj = ResourceManager.GetObject("PhucHoiDuLieu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QLKH_CN {
            get {
                object obj = ResourceManager.GetObject("QLKH_CN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QLKH_CN1 {
            get {
                object obj = ResourceManager.GetObject("QLKH_CN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QLQuaHanTra {
            get {
                object obj = ResourceManager.GetObject("QLQuaHanTra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QLQuaHanTra1 {
            get {
                object obj = ResourceManager.GetObject("QLQuaHanTra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QLSuVu {
            get {
                object obj = ResourceManager.GetObject("QLSuVu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QLSuVu1 {
            get {
                object obj = ResourceManager.GetObject("QLSuVu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QLThatLac {
            get {
                object obj = ResourceManager.GetObject("QLThatLac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QLThatLac1 {
            get {
                object obj = ResourceManager.GetObject("QLThatLac1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QTNguoiDung {
            get {
                object obj = ResourceManager.GetObject("QTNguoiDung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QTNguoiDung1 {
            get {
                object obj = ResourceManager.GetObject("QTNguoiDung1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuaDiaCau {
            get {
                object obj = ResourceManager.GetObject("QuaDiaCau", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuaDiaCau1 {
            get {
                object obj = ResourceManager.GetObject("QuaDiaCau1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quanlychuatra {
            get {
                object obj = ResourceManager.GetObject("Quanlychuatra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quanlychuatra1 {
            get {
                object obj = ResourceManager.GetObject("Quanlychuatra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quanlyden {
            get {
                object obj = ResourceManager.GetObject("quanlyden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quanlyden1 {
            get {
                object obj = ResourceManager.GetObject("quanlyden1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaoLuuDuLieu {
            get {
                object obj = ResourceManager.GetObject("SaoLuuDuLieu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaoLuuDuLieu1 {
            get {
                object obj = ResourceManager.GetObject("SaoLuuDuLieu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThamsoHT {
            get {
                object obj = ResourceManager.GetObject("ThamsoHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThamsoHT1 {
            get {
                object obj = ResourceManager.GetObject("ThamsoHT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThietLapTSHT {
            get {
                object obj = ResourceManager.GetObject("ThietLapTSHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThietLapTSHT1 {
            get {
                object obj = ResourceManager.GetObject("ThietLapTSHT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThongKe {
            get {
                object obj = ResourceManager.GetObject("ThongKe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThongKe1 {
            get {
                object obj = ResourceManager.GetObject("ThongKe1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TienichBC {
            get {
                object obj = ResourceManager.GetObject("TienichBC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TienichBC1 {
            get {
                object obj = ResourceManager.GetObject("TienichBC1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TimKiem {
            get {
                object obj = ResourceManager.GetObject("TimKiem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TimKiem1 {
            get {
                object obj = ResourceManager.GetObject("TimKiem1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tra {
            get {
                object obj = ResourceManager.GetObject("tra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tra1 {
            get {
                object obj = ResourceManager.GetObject("tra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TruyenLai {
            get {
                object obj = ResourceManager.GetObject("TruyenLai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TruyenLai1 {
            get {
                object obj = ResourceManager.GetObject("TruyenLai1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vcalendar {
            get {
                object obj = ResourceManager.GetObject("vcalendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vcalendar1 {
            get {
                object obj = ResourceManager.GetObject("vcalendar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vung {
            get {
                object obj = ResourceManager.GetObject("Vung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vung1 {
            get {
                object obj = ResourceManager.GetObject("Vung1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winrar {
            get {
                object obj = ResourceManager.GetObject("Winrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winrar1 {
            get {
                object obj = ResourceManager.GetObject("Winrar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
